name: Deploy Leptos to Deno Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Install Rust Nightly Toolchain, with Clippy & Rustfmt
      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: lint
        run: cargo clippy & cargo fmt

      - name: Install Wasm-Pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build step
        run: |
          deno task build
          # must manually remove the target directory, so it doesn't get uploaded to deno deploy
          rm -r target/

      - name: Upload to Deno Deploy
        id: deployment
        uses: denoland/deployctl@v1
        with:
          # This is the project name (first part of url) in Deno Deploy
          project: "leptos-deno-deploy"
          entrypoint: "run.ts"
          root: "." # ðŸ“ Update the root if necessary

      - name: Show deployment url
        run: |
          echo "Deployed at: " >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.deployment.outputs.url }} >> $GITHUB_STEP_SUMMARY
          Object.entries(${{ steps.deployment.outputs }}) >> $GITHUB_STEP_SUMMARY
          # | tail -n 3
          echo $GITHUB_STEP_SUMMARY
